DROP SCHEMA IF EXISTS chat CASCADE;
CREATE SCHEMA IF NOT EXISTS chat;

CREATE TABLE chat.User (
	id BIGSERIAL PRIMARY KEY,
	login VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(50) NOT NULL
);

CREATE TABLE chat.Chatroom (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(50) UNIQUE NOT NULL,
	owner BIGINT NOT NULL,
	FOREIGN KEY (owner)
		REFERENCES chat.User(id)
);

CREATE TABLE chat.Message (
	id BIGSERIAL PRIMARY KEY,
	author BIGINT NOT NULL,
	room BIGINT NOT NULL,
	text TEXT NOT NULL,
	time TIMESTAMP NOT NULL,
	FOREIGN KEY (author)
		REFERENCES chat.User(id),
	FOREIGN KEY (room)
		REFERENCES chat.Message(id)
);
