INSERT INTO product(identifier, name, price) VALUES(1, 'LAG', 99.99);
INSERT INTO product(identifier, name, price) VALUES(2, 'Panda', 99.99);
INSERT INTO product(identifier, name, price) VALUES(3, 'RoboNapoli', 99.99);
INSERT INTO product(identifier, name, price) VALUES(4, 'BiGDanno', 99.99);
INSERT INTO product(identifier, name, price) VALUES(5, 'Cybero', 99.99);
INSERT INTO product(identifier, name, price) VALUES(6, 'Scorpion', 99.99);
INSERT INTO product(identifier, name, price) VALUES(7, 'Devastator', 99.99);
INSERT INTO product(identifier, name, price) VALUES(8, 'Dark Franco', 99.99);
INSERT INTO product(identifier, name, price) VALUES(9, 'Arancino', 99.99);
INSERT INTO product(identifier, name, price) VALUES(10, 'Ultimate Weapon', 99.99);
